baseURL = 'https://r4sso.my'
languageCode = 'en'
title = 'r4sso.my'
theme = ["myTheme"]
pagerSize = 5
enableRobotsTXT = true

pygmentsUseClasses = true
pygmentsCodefences = true

[outputFormats.RSS]
  mediatype = "application/rss+xml"
  baseName = "rss" # This will generate the RSS feed as "index.xml"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[permalinks]
  posts = "/:year/:month/:title/"

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNumbersInTable = false
    noClasses = false
    

  [markup.goldmark.renderer]
    hardWraps = true

  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
    title = "Hello World!"
    description = "My personal website, blog and notes of r4sso"
    logo = "/images/logo.svg"
    favicon= "/images/logo.svg"
    tableOfContents = true
    github="r4sso"
    instagram="mfterm"
    mail="0xr4sso@proton.me"
    githubEditURL = "https://github.com/r4sso/r4sso.github.io/blob/main/content/"

[menu]
  [[menu.main]]
    name = "Blog"
    pageRef = "posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Notes"
    pageRef = "notes"
    url = "/notes/"
    weight = 2

  [[menu.main]]
    name = "Gallery"
    pageRef = "gallery"
    url = "/gallery/"
    weight = 3
  
  [[menu.main]]
    identifier = "more"
  name = "More"
  pageRef = "more"
  weight = 4

  [[menu.main]]
    parent = "more"
    name = "Category"
    pageRef = "categories"
    url = "/categories/"
    weight = 6
  [[menu.main]]
    parent = "more"
    name = "Tag"
    pageRef = "tags"
    url = "/tags/"
    weight = 7
  [[menu.main]]
    parent = "more"
    name = "Rss"
    pageRef = "rss"
    url = "/posts/rss.xml"
    weight = 8
  [[menu.main]]
    name = "?"
    pageRef = "about"
    url = "/about/"
    weight = 9

[privacy]
  [privacy.youtube]
    privacyEnhanced = true

